Allow usvg to process files with no viewBox and relative root dimensions.
RazrFalcon/resvg pull request #444
Opened 2021-08-31 15:24 UTC by reknih

As discussed in #40 today, here is a PR that allows files without a `viewBox` and with relative `width`s or `height`s to be converted into the Micro SVG format.

For this, the commit introduces the new `ViewportIntent` enumeration with the variants `Unknown` (default) and `PresetSize`.

- `Unknown` can be used for documents without relative units to fit a `viewBox` as tight around the path bounding boxes as possible
- `PresetSize` can also process relative units, but has to know the viewport size the SVG will be rendered into.

2021-08-31 15:50 UTC, RazrFalcon commented
I think the current implementation is too strict. Instead of using `ViewportIntent`, we can simply add `default_size: Size` to `Options`, which is set to 100x100 by default. This is a reasonable fallback and will simplify code/error processing quite a lot.

2021-08-31 15:59 UTC, RazrFalcon commented
Also, I think we can reuse existing `--width` and `--height` arguments. Not sure if anyone would want to use different target size and viewport size.

2021-09-01 12:51 UTC, reknih commented
Alright, I force-pushed a (way smaller) patch in line with your suggestions onto here.

For archival purposes, the first patch version is preserved on the `try-1` branch on my fork.

2021-09-01 13:58 UTC, RazrFalcon requested changes

2021-09-01 13:58 UTC, RazrFalcon commented on usvg/src/main.rs
> +        default_width:      input.opt_value_from_fn("--default-width", parse_length)?.unwrap_or(100),
Add to HELP.

2021-09-01 13:58 UTC, RazrFalcon commented
Looks good to me.

Don't worry about force-pushing, I will squash it anyway.

2021-09-01 13:59 UTC, RazrFalcon commented on usvg/src/main.rs
> +        default_width:      input.opt_value_from_fn("--default-width", parse_length)?.unwrap_or(100),
https://github.com/RazrFalcon/resvg/blob/2fba92c4c8ea1d463b25c7ab82c225dc13bb5a19/usvg/src/main.rs#L13

2021-09-01 14:21 UTC, merged

2021-09-01 14:22 UTC, RazrFalcon commented
Thanks again. I will publish a new version soon.